package coms6998.fall2016.data.models;

import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

import coms6998.fall2016.data.validation.CreateValidation;
import coms6998.fall2016.data.validation.UpdateValidation;

@DynamoDBTable(tableName = "__NO_TABLE_NAME__")
public abstract class BaseModel {

	private String key;
	private String uuid;
	private Long version;
	private Date createdOnTimestamp;
	private Date updatedOnTimestamp;

	@DynamoDBHashKey
	@NotNull(groups = CreateValidation.class, message = "[key] must be provided")
	@Null(groups = UpdateValidation.class, message = "[key] cannot be updated")
	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@DynamoDBAttribute
	@DynamoDBAutoGeneratedKey
	@Null(groups = { CreateValidation.class, UpdateValidation.class }, message = "[uuid] cannot be provided")
	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@DynamoDBVersionAttribute
	@Null(groups = { CreateValidation.class, UpdateValidation.class }, message = "[version] cannot be provided")
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@DynamoDBAttribute
	@Null(groups = { CreateValidation.class,
			UpdateValidation.class }, message = "[getCreatedOnTimestamp] cannot be provided")
	public Date getCreatedOnTimestamp() {
		return createdOnTimestamp;
	}

	public void setCreatedOnTimestamp(Date createdOnTimestamp) {
		this.createdOnTimestamp = createdOnTimestamp;
	}

	@DynamoDBAttribute
	@Null(groups = { CreateValidation.class,
			UpdateValidation.class }, message = "[getUpdatedOnTimestamp] cannot be provided")
	public Date getUpdatedOnTimestamp() {
		return updatedOnTimestamp;
	}

	public void setUpdatedOnTimestamp(Date updatedOnTimestamp) {
		this.updatedOnTimestamp = updatedOnTimestamp;
	}

	@Override
	public String toString() {
		return "BaseModel [key=" + key + ", uuid=" + uuid + ", version=" + version + ", createdOnTimestamp="
				+ createdOnTimestamp + ", updatedOnTimestamp=" + updatedOnTimestamp + "]";
	}

}
