import org.junit.Test;
//import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Jonathan' at '11/9/16 2:55 AM' with Gradle 3.1
 *
 * @author Jonathan, @date 11/9/16 2:55 AM
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		// Library classUnderTest = new Library();
		// assertTrue("someLibraryMethod should return 'true'",
		// classUnderTest.someLibraryMethod());
	}
}
